version: '3'

services:
  bookstoreapi:
    container_name: bookstore_api
    build:
      context: .
      dockerfile: '${PWD}/docker/prod.Dockerfile'
    env_file:
      - ./bookstore-prod.env
    command: /var/app/scripts/run_prod.sh
    image: bookstoreapi:latest
    depends_on:
      - base
      - bookstoreapi_db
    networks:
      - base-network

  bookstoreapi_db:
    container_name: bookstoreapi_db
    image: postgres
    restart: always
    env_file:
      - ./bookstore-prod.env
    ports:
      - '5432:5432'
    volumes:
      - bookstoreapi-db:/var/lib/postgresql/data
    networks:
      - base-network

  celery:
    env_file:
      - ./bookstore-prod.env
    image: bookstoreapi:latest
    command: >
      sh -c "celery -A bookstoreapi worker -B -D && celery worker -l info -A bookstoreapi"
    depends_on:
      - redis
      - bookstoreapi
    networks:
      - base-network

  nginx:
    build: ./nginx
    ports:
      - '8003:80'
    depends_on:
      - bookstoreapi
    volumes:
      - static_volume:/var/app/bookstoreapi/static
    networks:
      - base-network

volumes:
  static_volume:
  bookstoreapi-db:

